# .streamlit/secrets.toml template
# Rename this file to secrets.toml and fill in your details

[snowflake]
user = "RAJPRATHAM40"
password = "Pratham@123456"
account = "ONSHLZC-YV05307"
warehouse = "COMPUTE_WH"
database = "RAPID_RELIEF_DB"
schema = "CORE"
role = "ACCOUNTADMIN"
